export const genres: { [key: string]: string } = {
  Acción: "Action",
  Aventura: "Adventure",
  Animación: "Animation",
  Biografía: "Biography",
  Comedia: "Comedy",
  Crimen: "Crime",
  Documental: "Documentary",
  Drama: "Drama",
  Familiar: "Family",
  Fantasía: "Fantasy",
  "Cine Negro": "Film Noir",
  Historia: "History",
  Terror: "Horror",
  Musica: "Music",
  Musical: "Musical",
  Misterio: "Mystery",
  Romance: "Romance",
  "Ciencia Ficción": "Sci-Fi",
  Cortos: "Short Film",
  Deporte: "Sport",
  Superhéroes: "Superhero",
  Thriller: "Thriller",
  Guerra: "War",
  Western: "Western",
};

export const generos: { [key: string]: string } = {
  Action: "Acción",
  Adventure: "Aventura",
  Animation: "Animación",
  Biography: "Biografía",
  Comedy: "Comedia",
  Crime: "Crimen",
  Documentary: "Documental",
  Drama: "Drama",
  Family: "Familiar",
  Fantasy: "Fantasía",
  "Film Noir": "Cine Negro",
  History: "Historia",
  Horror: "Terror",
  Music: "Musica",
  Musical: "Musical",
  Mystery: "Misterio",
  Romance: "Romance",
  "Sci-Fi": "Ciencia Ficción",
  "Short Film": "Cortos",
  Sport: "Deporte",
  Superhero: "Superhéroes",
  Thriller: "Thriller",
  War: "Guerra",
  Western: "Western",
};
