export const genres = {
  Acción: "Action",
  Aventura: "Adventure",
  Animación: "Animation",
  Biografía: "Biography",
  Comedia: "Comedy",
  Crimen: "Crime",
  Documental: "Documentary",
  Drama: "Drama",
  Familiar: "Family",
  Fantasía: "Fantasy",
  "Cine Negro": "Film Noir",
  Historia: "History",
  Terror: "Horror",
  Musica: "Music",
  Musical: "Musical",
  Misterio: "Mystery",
  Romance: "Romance",
  "Ciencia Ficción": "Sci-Fi",
  Cortos: "Short Film",
  Deporte: "Sport",
  Superhéroes: "Superhero",
  Thriller: "Thriller",
  Guerra: "War",
  Western: "Western",
};
